AWSTemplateFormatVersion: 2010-09-09

Description: Cvicenie 5 - CloudWatch alarms

###########################################################################
# Useful CloudFormation docs
###########################################################################
# functions:         https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
# pseudo parameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
# pseudo attributes: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html
# template sections: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
###########################################################################

Parameters:
  EC2StackName:
    Description: Name of parent EC2 CloudFormation stack
    Type: String
    Default: ec2

Resources:
  PrivateASGHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: PrivateASGHighCPUAlarm
      AlarmDescription: Scale-up if CPU is greater than 90% for 1 minute in PrivateAutoScalingGroup
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 30
      EvaluationPeriods: 2
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref PrivateASGScaleUpPolicy
        - !Ref CPUAlarmsSNSTopic
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: !Sub ${EC2StackName}-PrivateAutoScalingGroupId

  PrivateASGScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName:
        Fn::ImportValue: !Sub ${EC2StackName}-PrivateAutoScalingGroupId
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      ScalingAdjustment: 2

  PrivateASGLowCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: PrivateASGLowCPUAlarm
      AlarmDescription: Scale-down if CPU is lesser than 70% for 1 minute in PrivateAutoScalingGroup
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 30
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref PrivateASGScaleDownPolicy
        - !Ref CPUAlarmsSNSTopic
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: !Sub ${EC2StackName}-PrivateAutoScalingGroupId

  PrivateASGScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName:
        Fn::ImportValue: !Sub ${EC2StackName}-PrivateAutoScalingGroupId
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      ScalingAdjustment: -1

  CPUAlarmsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CPUAlarmsSNSTopic
      Subscription:
        - Endpoint: mpekar@ohpen.com
          Protocol: email

  CPUAlarmsSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CPUAlarmsSNSTopic
      PolicyDocument:
        Id: CPUAlarmsSNSTopicPolicy
        Version: 2012-10-17
        Statement:
        - Sid: ManagePolicy
          Effect: Allow
          Principal:
            Service: cloudwatch.amazonaws.com
          Action:
            - sns:SetTopicAttributes
            - sns:RemovePermission
            - sns:ListSubscriptionsByTopic
            - sns:GetTopicAttributes
            - sns:DeleteTopic
            - sns:AddPermission
          Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:CPUAlarmsSNSTopic'
        - Sid: SubscribePolicy
          Effect: Allow
          Principal:
            Service: cloudwatch.amazonaws.com
          Action:
            - sns:Subscribe
            - sns:Publish
          Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:CPUAlarmsSNSTopic'